# Generated by Django 2.1.5 on 2019-02-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190206_2312'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='Blog',
        ),
        migrations.AlterModelTable(
            name='level',
            table='Level',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
    ]
